spring:
  application:
    name: teleport-api
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

server:
  servlet:
    context-path: /teleport
  port: 9999
  max-http-request-header-size: 512KB

download-path: D:\resouces\teleport-file\download
upload-path: D:\resouces\teleport-file\upload


